((emacs-lisp-mode
  . ((indent-tabs-mode . nil)
     (fill-column . 80)
     (elisp-lint-indent-specs . ((describe . 1)
                                 (xdescribe . 1)
                                 (it . 1)
                                 (xit . 1)
                                 (before-each . 0)
                                 (before-all . 0)
                                 (after-each . 0)
                                 (after-all . 0))))))
